import 'package:hive/hive.dart';
import 'release_file.dart';

part 'release.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 3)
class Release {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final DateTime? releaseDate;

  @HiveField(3)
  final String? artworkImagePath;

  @HiveField(4)
  final String? description;

  @HiveField(5)
  final List<String> trackIds; // List of MusicProject IDs

  @HiveField(6)
  final List<ReleaseFile> files; // List of supporting files

  Release({
    required this.id,
    required this.title,
    this.releaseDate,
    this.artworkImagePath,
    this.description,
    required this.trackIds,
    this.files = const [],
  });

  Release copyWith({
    String? id,
    String? title,
    DateTime? releaseDate,
    String? artworkImagePath,
    String? description,
    List<String>? trackIds,
    List<ReleaseFile>? files,
  }) {
    return Release(
      id: id ?? this.id,
      title: title ?? this.title,
      releaseDate: releaseDate ?? this.releaseDate,
      artworkImagePath: artworkImagePath ?? this.artworkImagePath,
      description: description ?? this.description,
      trackIds: trackIds ?? this.trackIds,
      files: files ?? this.files,
    );
  }
}
